All: true
SampleTransaction: false
SampleStruct: true
Txtpsblockdelay_start: true
Txtpsblockdelay_end: true
QueueDelay: true
TransactionThroughput: true
Txconfirmdelay_start: true
Txconfirmdelay_end: true
QueueDelay: true
TransmissionLatency: true
BandwitchUsage: true
Blockvalidefficy_total: true
Blockvalidefficy_txs: true
Cpumem: true
ReadStateDB: true
SampleConflict: true
WriteStateDB: true
ConsensusTbftCost: true
contract_time: true